import { defineConfig } from 'drizzle-kit'

/**
 * Turns `worker/schema.ts` into SQL in `migrations/`.
 *
 *   npm run db:generate     schema -> a numbered .sql file
 *   npm run db:migrate      apply them to the local D1
 *
 * `dialect: 'sqlite'` and no `dbCredentials` on purpose. D1 is SQLite, and
 * generating a migration only needs the schema file, not a database: drizzle-kit
 * diffs against its own journal in `migrations/meta/`. Applying is wrangler's
 * job, because only wrangler can reach a D1 binding.
 *
 * The schema itself is generated too, by `npm run db:schema`, and is not hand
 * written. `scripts/db-schema.ts` runs the `auth` CLI at exactly the installed
 * better-auth's version, because the CLI generates from its own bundled core.
 * The deprecated `@better-auth/cli` lags behind and omits the `account.issuer`
 * column; `auth@latest`, which this comment used to recommend, was 1.7.6 on 25
 * September 2026 and omits it too. That column is NOT NULL in the installed
 * 1.7.2, so a mismatch does not surface until the first sign-up fails.
 */
export default defineConfig({
  dialect: 'sqlite',
  /**
   * Two files, and the split matters.
   *
   * `schema.ts` is GENERATED by `npm run db:schema` and is overwritten whole.
   * `schema-app.ts` is ours and is not. Putting a table of ours in the
   * generated file would work until the next regeneration and then vanish
   * silently, taking the migration history's idea of reality with it.
   */
  schema: ['./worker/schema.ts', './worker/schema-app.ts'],
  out: './migrations',
})
