/**
 * Sprite sheets, out of the game's animation frames.
 *
 *   npm run sprites
 *
 * The extraction has every frame of every animation the game plays: 37 for the
 * item-consume burst, 25 to 45 for the location plates. Raw that is about a
 * megabyte per sequence, which is too much to ship for a flourish.
 *
 * A sheet is one strip PNG plus a CSS `steps()` animation, so it costs one
 * request, no JavaScript, and no per-frame decode. It also downsamples: an
 * effect drawn at 320 pixels does not need to arrive at 320 when it plays at
 * 96, and frames are dropped in pairs where a sequence is longer than the eye
 * can follow at 24 a second.
 *
 * Nothing here invents motion. The frames are the game's, in the game's order,
 * at the game's count.
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const ROOT = resolve(import.meta.dirname, '..')
const EXTRACTED = join(ROOT, 'extracted')
const OUT = join(ROOT, 'assets/sprites')

/** What to build, and how big it needs to be where it is used. */
const SHEETS = [
  { name: 'item-consume', from: 'gui/textures/GUI/ItemConsume', height: 96, keep: 2 },
  { name: 'boon-duo', from: 'gui/textures/GUI/Screens/BoonEntranceDuo', height: 128, keep: 2 },
  { name: 'boon-legendary', from: 'gui/textures/GUI/Screens/BoonEntranceLegendary', height: 128, keep: 2 },
]

/**
 * Composed with Pillow, because Node has no image library here and the project
 * already depends on Python for the extraction. The script is written out and
 * run rather than shelled per frame.
 */
function pythonFor(sheets: typeof SHEETS): string {
  return `
from PIL import Image
import os, json, sys

ROOT = ${JSON.stringify(ROOT)}
OUT = ${JSON.stringify(OUT)}
os.makedirs(OUT, exist_ok=True)
report = []

for sheet in ${JSON.stringify(sheets)}:
    folder = os.path.join(ROOT, "extracted", sheet["from"].replace("/", os.sep))
    if not os.path.isdir(folder):
        report.append({"name": sheet["name"], "error": "no such folder"})
        continue

    frames = sorted(f for f in os.listdir(folder) if f.lower().endswith(".png"))
    frames = frames[:: sheet["keep"]]
    if not frames:
        report.append({"name": sheet["name"], "error": "no frames"})
        continue

    images = []
    for f in frames:
        im = Image.open(os.path.join(folder, f)).convert("RGBA")
        ratio = sheet["height"] / im.height
        images.append(im.resize((max(1, round(im.width * ratio)), sheet["height"]), Image.LANCZOS))

    width = max(im.width for im in images)
    strip = Image.new("RGBA", (width * len(images), sheet["height"]), (0, 0, 0, 0))
    for i, im in enumerate(images):
        strip.paste(im, (i * width + (width - im.width) // 2, 0), im)

    path = os.path.join(OUT, sheet["name"] + ".png")
    strip.save(path, optimize=True)
    report.append({
        "name": sheet["name"],
        "frames": len(images),
        "frameWidth": width,
        "height": sheet["height"],
        "bytes": os.path.getsize(path),
    })

print(json.dumps(report))
`
}

const PYTHON = join(
  process.env.LOCALAPPDATA ?? '',
  'Programs/Python/Python312/python.exe',
)

if (!existsSync(EXTRACTED)) {
  console.log('no extracted/ directory, so there is nothing to build sheets from.')
  console.log('Re-create it with the deppth2 command in assets/README.md.')
  process.exit(0)
}

mkdirSync(OUT, { recursive: true })
const scriptPath = join(OUT, '.build.py')
writeFileSync(scriptPath, pythonFor(SHEETS))

const { spawnSync } = await import('node:child_process')
const run = spawnSync(PYTHON, [scriptPath], { encoding: 'utf8' })
if (run.status !== 0) {
  console.error(run.stderr || 'python failed')
  process.exit(1)
}

const report = JSON.parse(run.stdout.trim().split('\n').at(-1) ?? '[]') as {
  name: string
  frames?: number
  frameWidth?: number
  height?: number
  bytes?: number
  error?: string
}[]

console.log('sprite sheets in assets/sprites:')
const css: string[] = [
  '/* Generated by npm run sprites. Do not hand edit.',
  ' *',
  " * One strip per animation, played with steps(). No JavaScript, one request,",
  ' * and the frames are the game’s own in the game’s order.',
  ' */',
  '',
]

for (const sheet of report) {
  if (sheet.error || !sheet.frames) {
    console.log(`  ${sheet.name}: ${sheet.error}`)
    continue
  }
  console.log(
    `  ${sheet.name.padEnd(16)} ${sheet.frames} frames  ${sheet.frameWidth}x${sheet.height}  ${Math.round(
      (sheet.bytes ?? 0) / 1024,
    )} KB`,
  )
  const seconds = (sheet.frames / 24).toFixed(2)
  css.push(
    `.fx-${sheet.name} {`,
    `  width: ${sheet.frameWidth}px;`,
    `  height: ${sheet.height}px;`,
    `  background: url('/sprites/${sheet.name}.png') left center / auto 100% no-repeat;`,
    `  animation: fx-${sheet.name} ${seconds}s steps(${sheet.frames}) 1 both;`,
    '}',
    '',
    `@keyframes fx-${sheet.name} {`,
    `  to { background-position: -${(sheet.frameWidth ?? 0) * sheet.frames}px center; }`,
    '}',
    '',
  )
}

writeFileSync(join(ROOT, 'src/ui/sprites.css'), css.join('\n'))
console.log('\nsrc/ui/sprites.css written. Import it and add the class to an element.')
